name: Validate Terraform manifests with trivy

on:
  pull_request:

jobs:
  trivy:
    name: trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~1.9

      - name: Terraform Init
        run: terraform init

      - name: Run trivy with reviewdog output on the PR
        uses: reviewdog/action-trivy@v1
        with:
          trivy_command: config
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          filter_mode: diff_context
          fail_on_error: "true"
